
apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name:  apiedit
spec:
  selector:
    matchLabels:
      app:   apiedit
      tier:  api
  replicas: 
  template:
    metadata:
      labels:
        app:  apiedit
        tier: api
    spec:
      containers:
      - name:  apiedit
        image: acrforaksb.azurecr.io/repo/apiedit
        resources:
          requests:
            cpu: 20m
            memory: 60Mi
        env:
        - name: GET_HOSTS_FROM
          value: dns
          # If your cluster config does not include a dns service, then to
          # instead access environment variables to find service host
          # info, comment out the 'value: dns' line above, and uncomment the
          # line below:
          # value: env
        ports:
        - containerPort: 7774

