
apiVersion: v1
kind: Service
metadata:
  labels:
    app:  apidelete
    tier: api
  annotations:
    
  name: apidelete
spec:
  ports:
  - port: 7775
    protocol: TCP
    targetPort: 7775
  selector:
    app: apidelete
    tier: api
  type: ClusterIP
  
