
apiVersion: v1
kind: Service
metadata:
  labels:
    app:  mvcmoviefrontend
    tier: frontend
  annotations:
    
  name: mvcmoviefrontend
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: mvcmoviefrontend
    tier: frontend
  type: ClusterIP
  
