apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentity
metadata:
    name: "askkai123"               # The name of your Azure identity
spec:
    type: 0                                 # Set type: 0 for managed service identity
    resourceID: /subscriptions/e40fb554-c275-43ed-895f-f427a4e3f02c/resourcegroups/$resourceGroupName/providers/Microsoft.ManagedIdentity/userAssignedIdentities/askkai123
    clientID: "7d229ea2-2e80-42eb-a2ea-bd02b2ad78c5"     # The clientId of the Azure AD identity that you created earlier
---
apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentityBinding
metadata:
    name: azure-pod-identity-binding
spec:
    azureIdentity: "askkai123"      # The name of your Azure identity
    selector: azure-pod-identity-binding-selector
