
apiVersion: v1
kind: Service
metadata:
  labels:
    app:  apiget
    tier: api
  annotations:
    
  name: apiget
spec:
  ports:
  - port: 7771
    protocol: TCP
    targetPort: 7771
  selector:
    app: apiget
    tier: api
  type: ClusterIP
  
