apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: frontendkubemysql
spec:
  selector:
    matchLabels:
      app:  frontendkubemysql
      tier: frontend
  replicas: 
  template:
    metadata:
      labels:
        app:  frontendkubemysql
        tier: frontend
    spec:
      containers:
      - name: frontendkubemysql
        image: kaiacr.azurecr.io/myappkubemysql:latest
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
        env:
        - name: GET_HOSTS_FROM
          value: dns
          # If your cluster config does not include a dns service, then to
          # instead access environment variables to find service host
          # info, comment out the 'value: dns' line above, and uncomment the
          # line below:
          # value: env
        ports:
        - containerPort: 80
        volumeMounts:
        - name: appsettings-json
          mountPath: /app/appsettings.json
          subPath: appsettings.json
      volumes:
      - name: appsettings-json
        configMap:
         name: appsettings-json-kubemysql
