apiVersion: v1
kind: Service
metadata:
  labels:
    app: phpmyadmin-azuremysql
  name: phpmyadmin-frontend-azuremysql
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: phpmyadmin-azuremysql
  type: LoadBalancer
